### ISSUE TITLE
Configuración inicial del proyecto 

### ISSUE THREAD

**Issue by WhitneySt** [MAKAIABootcamp/corpoAyapelEcommerce-project-front-4#2]
- [x] Ejecutar cli npx create react app
- [x] Instalar las principales dependencias

> redux 
> redux toolkit
> redux - thunk
> react router dom
> firebase
>axios 
> formik 
> yup
> sweet alert
> sass
> material iu 
> bootstrap
> chakra
- [x] Enlazarlo al repositorio proporcionado.

**Comment by PaolaTorresV** [comment]
first issue
