### ISSUE TITLE
Crear el App Router 

### ISSUE THREAD

**Issue by PaolaTorresV** [MAKAIABootcamp/corpoAyapelEcommerce-project-front-4#9]
- [x] Definir rutas privadas
- [x] Definir rutas públicas

import React, { useEffect, useState } from "react";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { ChakraProvider } from "@chakra-ui/react";
import PublicRouter from "./PublicRouter";
import PrivateRouter from "./PrivateRouter";
import Login from "../pages/Login";
import Home from "../pages/Home";
import NotFound from "../pages/NotFound";
import Details from "../pages/Details";
import Search from "../pages/Search";
import GlobalStyles from "../components/styles/GlobalStyle";
import CreateAccount from "../pages/CreateAccount";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../firebase/firebaseConfig";
import { useDispatch, useSelector } from "react-redux";
import { loginActionSync } from "../redux/actions/userActions";
import UsuarioProfile from "../pages/UsuarioProfile";
import CurrentOrder from "../pages/CurrentOrder";
import OrderAccepted from "../pages/OrderAccepted";

const AppRouter = () => {
  const [isLoggedIn, setIsLoggedIn] = useState(null);
  const dispatch = useDispatch();

  const { user } = useSelector((store) => store.user);
  console.log(user);

  useEffect(() => {
    onAuthStateChanged(auth, (userLogged) => {
      if (userLogged?.uid) {
        setIsLoggedIn(true);

        if (!Object.entries(user).length) {
          console.log("No hay info");
          const logged = {
            email: userLogged.auth.currentUser.email,
            name: userLogged.auth.currentUser.displayName,
            avatar: userLogged.auth.currentUser.photoURL,
            accessToken: userLogged.auth.currentUser.accessToken,
          };
          dispatch(loginActionSync(logged));
        }
        console.log(userLogged);
      } else {
        setIsLoggedIn(false);
      }
    });
  }, [user, dispatch]);

return (
    <BrowserRouter>
      <Routes>
        <Route path="/">
          <Route element={<PublicRouter isAuthentication={isLoggedIn} />}>
            <Route index element={<Login />} />
            <Route path="home" element={<Home />} />
            <Route path="/details/:id" element={<RestaurantsDetails />} />
            <Route path="TopSell" element={<SectionTopSell />} />
            <Route path="News" element={<SectionNews />} />
            <Route path="Testimony" element={<SectionTestimony />} />
            <Route path="Handicrafts" element={<SectionHandicrafts />} />
            <Route path="AboutUs" element={<SectionAboutUs />} />
            <Route path="Cart" element={<Cart />} />
            <Route path="Contact" element={<Contact />} />
            <Route path="TearmsAndConditions" element={<TearmsAndConditions/>} />
            <Route path="search" element={<Search />}/> 
            <Route path="createaccount" element={<CreateAccount />}/> 

          <Route element={<PrivateRouter is Authentication={isLoggedIn} />}>
            <Route path="order" element={<OrderAccepted />} />
            <Route path="InfoShipping" element={<InfoShipping />} />
            <Route path="SuccesPurchase" element={<SuccesPurchase />} />
            <Route path="pay" element={<CurrentOrder/>} />
            <Route path="AdmGeneral" element={<AdmGeneral />} />
            <Route path="Adm1" element={<Adm1 />} />
            <Route path="Adm2" element={<Adm2 />} />
            <Route path="Adm3" element={<Adm3 />} />
        </Route>
        <Route path="*" element={<NotFound />} />
      </Routes>
    </BrowserRouter>
    <GlobalStyles />
);
};

export default AppRouter;

**Comment by AndresParra11** [comment]
Se realizó la modificación prevista donde se dejó solamente las rutas públicas y con lógica se establecen que las de Admin, cart y payment son las que se pueden acceder solamente cuando se loguee alguien.
